"""Type stubs for scripts.config module."""

from pathlib import Path
from typing import Any, Optional

class ConfigProvider:
    def __init__(self, workspace_root: str = ".") -> None: ...
    def get_workspace_root(self) -> str: ...
    def get_recordings_mount(self) -> str: ...
    def get_ffmpeg_path(self) -> str: ...
    def get_default_profile(self) -> str: ...
    def get_profile(self, profile_name: str = "default") -> dict[str, Any]: ...
    def get_profile_voice_extract_settings(
        self, profile_name: str = "default"
    ) -> dict[str, Any]: ...
    def get_all_profiles(self) -> list[str]: ...
    def get_profile_silence_threshold(self, profile_name: str = "default") -> float: ...
    def get_profile_silence_min_duration(self, profile_name: str = "default") -> float: ...
    def get_profile_enable_cutting(self, profile_name: str = "default") -> bool: ...
    def get_profile_collapse_to(self, profile_name: str = "default") -> float: ...
    def get_profile_trim_pad_before(self, profile_name: str = "default") -> float: ...
    def get_profile_trim_pad_after(self, profile_name: str = "default") -> float: ...
    def get_profile_remove_fillers(self, profile_name: str = "default") -> bool: ...
    def get_profile_filler_confidence_threshold(self, profile_name: str = "default") -> float: ...
    def get_profile_low_energy_min_duration(self, profile_name: str = "default") -> float: ...
    def get_profile_target_duration(self, profile_name: str = "default") -> Optional[float]: ...
    def get_profile_max_duration(self, profile_name: str = "default") -> Optional[float]: ...
    def get_profile_caption_words_per_line(self, profile_name: str = "default") -> int: ...
    def get_profile_caption_style(self, profile_name: str = "default") -> str: ...
    def get_profile_pip_position(self, profile_name: str = "default") -> str: ...
    def get_profile_pip_size_ratio(self, profile_name: str = "default") -> float: ...
    def get_profile_aspect_ratio(self, profile_name: str) -> str: ...
    def get_profile_resolution(self, profile_name: str) -> str: ...
    def get_loudnorm_targets(self, profile_name: str) -> dict[str, float]: ...
    def get_brand(self) -> dict[str, Any]: ...
    def get_brand_font(self) -> str: ...
    def get_brand_colors(self) -> dict[str, str]: ...
    def get_voice_extract_settings(self) -> dict[str, Any]: ...
    def get_arnndn_model_path(self) -> str: ...
    def get_arnndn_settings(self) -> dict[str, Any]: ...
    def get_highpass_settings(self) -> dict[str, int]: ...
    def get_afftdn_settings(self) -> dict[str, int]: ...
    def get_agate_settings(self) -> dict[str, float]: ...
    def get_eq_settings(self) -> dict[str, Any]: ...
    def get_loudnorm_settings(self) -> dict[str, Any]: ...
    def get_stereo_settings(self) -> dict[str, float]: ...
    def get_compressor_settings(self) -> dict[str, float]: ...
    def get_diagnostic_settings(self) -> dict[str, Any]: ...

_config: Optional[ConfigProvider] = None

def get_config(workspace_root: str = ".") -> ConfigProvider: ...
