"""Type stubs for scripts.preset_manager module."""

from typing import Any, Optional

class PresetManager:
    def __init__(self, workspace_root: str = ".") -> None: ...

    # Subtitle presets
    def get_subtitle_presets(self) -> dict[str, Any]: ...
    def get_subtitle_preset(self, name: str) -> Optional[dict[str, Any]]: ...
    def get_default_subtitle_preset(self) -> dict[str, Any]: ...
    def list_subtitle_presets(self) -> list[dict[str, Any]]: ...
    def create_subtitle_preset(self, name: str, preset: dict[str, Any]) -> None: ...
    def update_subtitle_preset(self, name: str, preset: dict[str, Any]) -> None: ...
    def delete_subtitle_preset(self, name: str) -> bool: ...

    # Audio presets
    def get_audio_presets(self) -> dict[str, Any]: ...
    def get_audio_preset(self, name: str) -> Optional[dict[str, Any]]: ...
    def list_audio_presets(self) -> list[dict[str, Any]]: ...
    def create_audio_preset(self, name: str, preset: dict[str, Any]) -> None: ...
    def update_audio_preset(self, name: str, preset: dict[str, Any]) -> None: ...
    def delete_audio_preset(self, name: str) -> bool: ...

    # Color presets
    def get_color_presets(self) -> dict[str, Any]: ...
    def get_color_preset(self, name: str) -> Optional[dict[str, Any]]: ...
    def list_color_presets(self) -> list[dict[str, Any]]: ...
    def create_color_preset(self, name: str, preset: dict[str, Any]) -> None: ...
    def update_color_preset(self, name: str, preset: dict[str, Any]) -> None: ...
    def delete_color_preset(self, name: str) -> bool: ...

_preset_manager: Optional[PresetManager] = None

def get_preset_manager(workspace_root: str = ".") -> PresetManager: ...
