"""Type stubs for scripts.utils.session module."""

from pathlib import Path
from typing import Any, Optional

class SessionManager:
    workspace_root: Path
    sessions_dir: Path

    def __init__(self, workspace_root: str) -> None: ...
    def session_exists(self, session_id: str) -> bool: ...
    def get_session_path(self, session_id: str) -> Path: ...
    def save_session(self, session: Any) -> None: ...
    def load_session(self, session_id: str) -> Any: ...
    def list_sessions(self) -> list[Any]: ...
    def create_session(
        self,
        session_id: str,
        topic: str,
        profile: str = ...,
        goal: str = ...,
        tone: str = ...,
        cta: str = ...,
        duration: int = ...,
    ) -> Any: ...
    def update_status(self, session_id: str, status: str) -> None: ...
    def get_next_stage(self, session_id: str) -> Optional[str]: ...

def load_settings(workspace_root: str) -> dict[str, Any]: ...
def load_profile(profile_name: str, workspace_root: str) -> dict[str, Any]: ...
def load_brand(workspace_root: str) -> dict[str, Any]: ...
def load_filler_words(workspace_root: str) -> list[str]: ...
def ensure_session_dirs(workspace_root: str, session_id: str) -> None: ...
